### ISSUE TITLE
Створити єдину бібліотеку

### ISSUE THREAD

**Issue by indrekis** [DariaMinieieva/Freenove_4WD_Car_Kit_for_ESP32#3]
Зараз є проблема -- код роботи з, власне, машинкою, продубльований у купі місць. Це дуже ускладнює документування і переклад. Ніби немає технічних причин, чому так має бути. Або, принаймні, чому це дублювання не можна зменшити на порядок і більше. 

Пропоную виділити спільний код в окрему бібліотеку, після завершення -- оформити її як бібліотеку Arduino та додати у відповідні репозиторії Arduino IDE. Тоді можна буде її документувати та перекласти документацію один раз.

Корисним це буде також на робоклубі ФПН та деяких інших курсах. 

Створив [бранч під це](https://github.com/LeaveNoOneBehind/Freenove_4WD_Car_Kit_for_ESP32/tree/unified_lib).

**Comment by redn1nja** [comment]
https://arduino.github.io/arduino-cli/1.0/library-specification/

https://github.com/arduino/library-registry/blob/main/FAQ.md#submission-requirements
https://docs.arduino.cc/learn/contributions/arduino-creating-library-guide/
